### PR TITLE
WIP: Add CI Working Group Meeting Time

### PR DESCRIPTION
**Pull request by hh**
I'd like to start meeting on a twice-monthly basis, but we need to figure out a time.
I'm suggesting two options:

*  2nd and 4th Tuesday 8am PT

OR

* 1st and 3rd Wednesday 10am PT.

### CODE REVIEW

**Comment by hh** [comment]
Do we have a public calendar managed by cncf to put this on?

**Comment by dankohn** [comment]
CNCF public calendar is at https://goo.gl/eyutah. Just let me know what you decide and we'll add them.

Note that [bi-weekly](https://en.wikipedia.org/wiki/Biweekly) has two meanings and so is not a good word to use. Your proposed time is weekly, so I presume you wanted to choose one of the options. I'd prefer the Wednesday options, as we have an internal CNCF meeting on the Tuesdays.

Cc @atarfish9 @caniszczyk

**Comment by hh** [comment]
Updated initial comment to be clear I was suggesting two twice-monthly options.

**Comment by clintkitson** [comment]
I think Wednesday would have the least overlap at this point.

**Comment by hh** [comment]
@quinton-hoole sent out an invite and an 8am Pacific Time Slot for Tuesdays
https://lists.cncf.io/pipermail/cncf-ci-public/2017-May/000046.html
@clintkitson does that work for you?

**Comment by clintkitson** [comment]
8a Tuesday is the CNCF technical oversight committee recurring meeting every other week. If it happened the 30th of May, and then every two weeks following it would not overlap.

**Comment by dankohn** [comment]
It will still get messed up in months that have 5 Tuesdays. 

TOC meeting is 1st and 3rd Tuesdays. WG-CI should meet 2nd and 4th Tuesdays. (In Google Calendar, that requires two invitations. )

--
Dan Kohn <mailto:dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation <https://cncf.io>
tel:+1-415-233-1000

**Comment by quinton-hoole** [comment]
SGTM

**Comment by quinton-hoole** [comment]
I've updated the calendar invite to two separate ones, one for the 2nd, and another for the 4th Tue, as Dan suggested.

**Comment by hh** [comment]
Thanks Quinton.

Seems we have a quorum:

https://github.com/cncf/wg-ci#meeting-time

**Pull request merged**
